services:
  web-app:
    build: ./app
    image: flaskAppImg
    container_name: flaskAppCont
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: nginxCont
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - web-app